name: Artifacts
description: Upload and download artifacts
author: https://github.com/buildkite
requirements: []
configuration:
  properties:
    upload:
      type: [ string, array ]
    download:
      type: [ string, array ]
    step:
      type: string
    build:
      type: string
  oneOf:
    - required:
      - upload
    - required:
      - download
  additionalProperties: false