name: Artifacts
description: Upload and download artifacts
author: https://github.com/buildkite
requirements:
  - bash
configuration:
  definitions:
    from-to-object:
      type: object
      properties:
        from:
          type: string
        to:
          type: string
      required:
        - from
        - to
  properties:
    upload:
      oneOf:
        - $ref: '#/definitions/from-to-object'
        - type: string
        - type: array
          items:
            type: string
        - type: array
          items:
            $ref: '#/definitions/from-to-object'
    download:
      oneOf:
        - $ref: '#/definitions/from-to-object'
        - type: string
        - type: array
          items:
            type: string
        - type: array
          items:
            $ref: '#/definitions/from-to-object'
    step:
      type: string
    build:
      type: string
    s3-upload-acl:
      type: string
    gs-upload-acl:
      type: string
    compressed:
      type: string
      pattern: '.*(.zip|.tgz)$'
  oneOf:
    - required:
      - upload
    - required:
      - download
  additionalProperties: false
